Resources:
   vpc1:
     Type: AWS::EC2::VPC
     Properties: 
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: firstvpc
   vpc2:
     Type: AWS::EC2::VPC
     Properties: 
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: Secondvpc
   subnet1:
     Type: AWS::EC2::Subnet
     Properties:
      VpcId: !Ref vpc1
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: Name
          Value: firstsubnet
   subnet2:
     Type: AWS::EC2::Subnet
     Properties:
      VpcId: !GetAtt vpc2.VpcId
      CidrBlock: 10.0.2.0/24
      Tags:
        - Key: Name
          Value: secondsubnet

Outputs:
  vpc1id:
    Description: VPC ID of first VPC
    Value: !Ref vpc1
    Export:
      Name: vpc1id
  vpc2id:
    Description: VPC ID of second VPC
    Value: !Ref vpc2
