Resources:
   vpc1:
     Type: AWS::EC2::VPC
     Properties: 
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: firstvpc
   vpc2:
     Type: AWS::EC2::VPC
     Properties: 
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: Secondvpc
   subnet1:
     Type: AWS::EC2::Subnet
     Properties:
      VpcId: !Ref vpc1
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: Name
          Value: firstsubnet
   subnet2:
     Type: AWS::EC2::Subnet
     Properties:
      VpcId: !GetAtt vpc2.VpcId
      CidrBlock: 10.0.2.0/24
      Tags:
        - Key: Name
          Value: secondsubnet
   routetable1:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId: !Ref vpc1
        Tags:
          - Key: Name
            Value: firstroutetable
   routetable2:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId: !GetAtt vpc2.VpcId
        Tags:
          - Key: Name
            Value: secondroutetable
   subnet1RouteTableAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        SubnetId: !Ref subnet1
        RouteTableId: !Ref routetable1
        Tags:
          - Key: Name
            Value: firstsubnetroutetableassociation
   subnet2RouteTableAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        SubnetId: !Ref subnet2
        RouteTableId: !Ref routetable2
        Tags:
         - Key: Name
           Value: secondsubnetroutetableassociation
   securitygroup1:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: first security group
        VpcId: !Ref vpc1
        Tags:
          - Key: Name
            Value: firstsecuritygroup
   securityrules:
      Type: AWS::EC2::SecurityGroupIngress
      Properties:
        GroupId: !Ref securitygroup1
        IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
  

Outputs:
  vpc1id:
    Description: VPC ID of first VPC
    Value: !Ref vpc1
    Export:
      Name: vpc1id
  vpc2id:
    Description: VPC ID of second VPC
    Value: !Ref vpc2
