Parameters:
  vpc1Id:
    Description: VPC ID of first vpc
    Type: String
    Default: null
Resources:
   subnet1:
     Type: AWS::EC2::Subnet
     Properties:
      VpcId: !Ref vpc1Id
      CidrBlock: 10.0.1.0/24
