Resources:
   vpc1:
     Type: AWS::EC2::VPC
     Properties: 
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: firstvpc
   vpc2:
     Type: AWS::EC2::VPC
     Properties: 
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: Secondvpc
outputs:
  vpc1id:
    Description: VPC ID of first VPC
    Value: !Ref vpc1
    Export:
      Name: "vpc1id"
  vpc2id:
    Description: VPC ID of second VPC
    Value: !Ref vpc2
