AWSTemplateFormatVersion: '2010-09-09'
Resources:
  myStackWithParams:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cfn-template-vis/vpc.yaml
      Parameters:
        cidrblock: 10.0.0.0/16
