AWSTemplateFormatVersion: '2010-09-09'
Resources:
  myStackWithParams:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cfn-template-vis/vpc.yaml
      Parameters:
        cidrblock: 10.0.0.0/16
  subnetStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cfn-template-vis/subnet.yaml
      Parameters:
        vpc1: !GetAtt myStackWithParams.Outputs.vpc1Id
        subnet1Cidr: 10.0.1.0/24
