Parameters:
  vpc1:
    Type: String
    Description: VPC ID for the first subnet
  subnet1Cidr:
    Type: String
    Description: CIDR block for the first subnet
Resources:
    subnet1:
     Type: AWS::EC2::Subnet
     Properties:
      VpcId: !Ref vpc1
      CidrBlock: !Ref subnet1Cidr
      Tags:
        - Key: Name
          Value: firstsubnetnested