Parameters:
  vpc1:
    Type: String
    Description: VPC ID for the first subnet
  vpc2:
    Type: String
    Description: VPC ID for the second subnet
Resources:
    subnet1:
     Type: AWS::EC2::Subnet
     Properties:
      VpcId: !Ref vpc1
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: Name
          Value: firstsubnetnested