Parameters:
  cidrblock:
    Type: String
    Default: 10.0.0.0/16
Resources:
   vpc1:
     Type: AWS::EC2::VPC
     Properties: 
      CidrBlock: !Ref cidrblock
      Tags:
        - Key: Name
          Value: firstvpcnested
Outputs:
  vpc1Id:
    Description: VPC ID of first vpc
    Value: !GetAtt vpc1.VpcId